apiVersion: v1
kind: Service
metadata:
  name: classzz
  namespace: default
spec:
  ports:
    - port: 8333
      targetPort: 8333
  selector:
    service: classzz
  type: LoadBalancer
  externalTrafficPolicy: Local
